# Generated by Django 5.0.5 on 2024-05-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_image", models.ImageField(upload_to="processed/")),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.uploadedimage",
                    ),
                ),
            ],
        ),
    ]
