# Generated by Django 5.0.5 on 2024-05-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0002_processedimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="processedimage", name="processed_at",),
        migrations.RemoveField(model_name="processedimage", name="processed_image",),
        migrations.AddField(
            model_name="processedimage",
            name="image",
            field=models.ImageField(null=True, upload_to="processed_images/"),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="uploaded_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="image_processing.uploadedimage",
            ),
        ),
    ]
