# Generated by Django 5.0.5 on 2024-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0003_remove_processedimage_processed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="image",
            field=models.ImageField(null=True, upload_to="processed/"),
        ),
    ]
