# Generated by Django 5.0.5 on 2024-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0004_alter_processedimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="num_clusters",
            field=models.IntegerField(default=4),
        ),
    ]
