# Generated by Django 5.0.5 on 2024-05-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0005_uploadedimage_num_clusters"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="threshold",
            field=models.IntegerField(default=70),
        ),
    ]
