# Generated by Django 5.0.5 on 2024-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0006_uploadedimage_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="edged_image",
            field=models.ImageField(null=True, upload_to="processed/"),
        ),
    ]
