# Generated by Django 5.0.5 on 2024-05-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0007_processedimage_edged_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="processedimage", name="edged_image",),
        migrations.CreateModel(
            name="EdgesImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edged_image", models.ImageField(null=True, upload_to="edged/")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.processedimage",
                    ),
                ),
            ],
        ),
    ]
