# Generated by Django 5.0.5 on 2024-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0008_remove_processedimage_edged_image_edgesimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedimage", name="threshold",),
        migrations.AddField(
            model_name="edgesimage",
            name="threshold",
            field=models.IntegerField(default=70),
        ),
    ]
