# Generated by Django 5.0.5 on 2024-05-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0010_rename_image_edgesimage_processed_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edgesimage", old_name="processed_image", new_name="image",
        ),
    ]
