# Generated by Django 5.0.5 on 2024-05-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0012_uploadedimageauto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="uploaded_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="image_processing.uploadedimageauto",
            ),
        ),
    ]
