# Generated by Django 5.0.5 on 2024-05-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_processing", "0013_alter_processedimage_uploaded_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedimage",
            name="uploaded_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="image_processing.uploadedimage",
            ),
        ),
        migrations.CreateModel(
            name="ProcessedImageAuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(null=True, upload_to="processed/"),
                ),
                (
                    "uploaded_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="image_processing.uploadedimageauto",
                    ),
                ),
            ],
        ),
    ]
